# Configuración para el entorno de desarrollo en Docker Compose
spring.datasource.url=jdbc:postgresql://db:5432/facturacion
spring.datasource.username=facturacion_user
spring.datasource.password=facturacion
spring.datasource.driver-class-name=org.postgresql.Driver
